# Generated by Django 3.1.7 on 2021-04-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0003_auto_20210419_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Номер телефона'),
        ),
    ]
