# Generated by Django 3.1.7 on 2021-04-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0008_auto_20210422_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.CharField(max_length=255, verbose_name='URL картинки'),
        ),
    ]
