# Generated by Django 3.1.7 on 2021-04-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0009_auto_20210423_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='shipping_adress',
            new_name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='email',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='receiver',
        ),
        migrations.AddField(
            model_name='purchase',
            name='items',
            field=models.JSONField(null=True, verbose_name='Id товара'),
        ),
    ]
