# Generated by Django 3.1.7 on 2021-04-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0011_remove_purchase_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='items',
            field=models.JSONField(null=True, verbose_name='Товары'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payload',
            field=models.IntegerField(null=True, verbose_name='ID заказа'),
        ),
    ]
