# Generated by Django 3.1.7 on 2021-04-24 18:47

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0012_auto_20210425_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='shipping_address',
            field=jsonfield.fields.JSONField(null=True, verbose_name='Адрес доствки'),
        ),
    ]
