# Generated by Django 3.1.7 on 2021-04-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0013_auto_20210425_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='phone_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Номер телефона'),
        ),
    ]
